### ISSUE TITLE
How to install i am new to kali linux 

### ISSUE THREAD

**Issue by RootAndroid58** [bl4ckbo7/agt#1]
sir i googled but i cant find the solution i git cloned ur repositories i ran ./agt but it gives this error 
```[x] Oops! Can't find module, or can't find name in module!
Traceback (most recent call last):
  File "./agt", line 14, in <module>
    import git
ModuleNotFoundError: No module named 'git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./agt", line 53, in <module>
    sys.exit(1)`
NameError: name 'sys' is not defined
```
also installed requirement using pip can u plz help 1 time help

**Comment by bl4ckbo7** [comment]
Sorry, for late reply. But that it seems that you didn't install **git** package in your linux machine. So install it with _sudo apt install git_ comamnd.

**Comment by bl4ckbo7** [comment]
Sorry, for late reply. But that it seems that you didn't install **git** package in your linux machine. So install it with _sudo apt install git_ command.
